### ISSUE TITLE
ng-docs is putting generated files in eureka-webapp/src on compile

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#100]
These should be going into the target folder somewhere.

**Comment by candyam5522** [comment]
From what I see, the ng-docs folder is already in the target folder
![screen shot 2016-07-06 at 1 40 45 pm](https://cloud.githubusercontent.com/assets/5263886/16628408/aa1ecf9e-437f-11e6-8d05-d02ee7bac372.png)
![screen shot 2016-07-06 at 1 41 08 pm](https://cloud.githubusercontent.com/assets/5263886/16628413/addd5114-437f-11e6-9be8-6543608f9b46.png)

Correct me if I understand it wrong.

**Comment by arpost** [comment]
The file eureka-webapp/src/main/webapp/ng-docs/js/docs-setup.js keeps changing when running mvn install. The build process seems to alternate between adding a bunch of lines and then taking them out.

**Comment by candyam5522** [comment]
not enable to reproduce it, neither me nor Akshatha. Not related to eureka project. Configuration/set-up error

**Comment by arpost** [comment]
The problem appears to be that the contents of the ng-docs directory are intended to be generated by the build process and can change despite no relevant code changes for a yet-unknown reason. Assuming that the contents do get rebuilt in their entirety if ng-docs is removed, the best solution appears to be to remove ng-docs/** from version control and add the ng-docs directory to .gitignore.
