### ISSUE TITLE
Shows HTML markup in message for registering an account that already exists

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#109]
After pushing submit, says: 
Account already exists! You may <a href="/login">go ahead and login</a>.

![screen shot 2016-07-18 at 3 22 19 pm](https://cloud.githubusercontent.com/assets/5026087/16927536/c0704f9a-4cfb-11e6-8f7c-02f01b468f77.png)

**Comment by candyam5522** [comment]
I fixed the bug and test with LOCAL user already. It looks like this now when you try to register the same user twice:
<img width="659" alt="screen shot 2016-07-19 at 11 23 37 am" src="https://cloud.githubusercontent.com/assets/5263886/16955979/a86b0f1c-4da4-11e6-8a6b-3fe0231254e2.png">

Basically I:
1. remove the html tag from Messages.properties file
2. insert the html tag again with jQuery code in eureka.registration.js file
Nothing change on JSP page and Servlet page
If you think the UI looks good, I will pull a request.
