### ISSUE TITLE
Cannot save cohort properly

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#139]
The js file that cohort page uses: eureka.cohort.js has an ajax call to get user info which using url:
url: '**../proxy-resource/users/me**'
which now cannot get proper user info anymore, and this calls problem while saving the corhort.

**Comment by arpost** [comment]
I'm going to close this and create another issue for switching it back (once we update eureka with the new proxy).

**Comment by arpost** [comment]
Eureka should still be able to have its own ../proxy-resource/users/me call, because it has the standard USERS table that every other module has (except eurekaclinical-user-service, which has an expanded set of columns on its USERS table). This issue is resolved.
