### ISSUE TITLE
Do research on SmartTable, ui-grid and ng-table

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#151]

**Comment by candyam5522** [comment]
**Smart table**
Pro:  
It is an AngularJS module(_angular.module('myApp',['smart-table']_), lightweight(JS code is 4kb in total), no dependencies other than Angular itself.
Cons:
Advanced features(search)? running slow for large number row?
Available resources?
Smart table doesn't perform very well for sorting when you get up around 10,000 rows
Pagination on smart table is really ugly

(http://stackoverflow.com/questions/21375073/best-way-to-represent-a-grid-or-table-in-angularjs-with-bootstrap-3)

**ui-grid (Angular UI grid)**
Pro:
Native AngularJS implementation, no jQuery
Performs well with large data sets; even 10,000+ rows
Cons:
Is it easy to implement? lightweight or not? available resources (doc, example, how many people use it? active maintained?)

**ng-table**
Pros:
Great documentations, and examples, better styling
Cons:
Maintained by a single person? Performance on lot of data(slow)?

Have you consider ng-grid (looks popular)?
What is our priority?
Easy to implement?
Easy to maintain?
Fast to build?
Performance over 1000+row?
Search function?
Others?

Choice has to be made base on our priority

**Comment by arpost** [comment]
Completed
