### ISSUE TITLE
Run and test all REST APIs

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#152]
- provide example URLs and return result for all working REST APIs

- move user-service related REST APIs to user-service project, create another WiKi page over there(https://github.com/eurekaclinical/eurekaclinical-user-service/wiki/REST-APIs)

- document all the problematic ones

- assign priorities to fix all problematic ones

**Comment by candyam5522** [comment]
- report for GET APIs has been submitted to Andrew
- will make a fix list base on priority

**Comment by arpost** [comment]
Completed.
