### ISSUE TITLE
Hardcoded eureka-webapp

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#17]
eureka-webapp is hardcoded few places, this affects the reusability of our code. 

For example, at eureka.cohorts.js, currently I use:
url: '/eureka-webapp/proxy-resource/destinations'

Problem is:
if I change to '/proxy-resource/destinations', the url changes to: https://localhost:8443/proxy-resource/destinations
if I change to 'proxy-resource/destinations', the url changes to:  https://localhost:8443/eureka-webapp/protected/proxy-resource/destinations

There are other places like this, need to figure out a better way than hardcoded url path.

<img width="1068" alt="screen shot 2016-01-06 at 1 01 00 pm" src="https://cloud.githubusercontent.com/assets/5263886/12150106/c3daa8c0-b475-11e5-9ca9-8eab8908fa66.png">
<img width="1285" alt="screen shot 2016-01-06 at 1 01 10 pm" src="https://cloud.githubusercontent.com/assets/5263886/12150109/c6bf2b74-b475-11e5-8a3e-138fbdd093c5.png">

![screen shot 2016-01-06 at 11 46 31 am](https://cloud.githubusercontent.com/assets/5263886/12149768/90e74f6a-b473-11e5-9c5f-89b50cdad70b.png)

**Comment by arpost** [comment]
I see what the problem is now. We're no longer on the index.html page, we're on a page in the /protected directory. Hence, /protected is the working directory. Try using ../proxy-resource/destinations.
