### ISSUE TITLE
Angular-lize job page

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#173]

**Comment by arpost** [comment]
Current status (from candyam5522):

Display, 90% works, the only thing left behind is date-time picker, I have code there(main.html), but for some reason it does not work now, the developer whoever take over this assignment needs to debug it.

What is left behind:

1. Tree component, Jason to provide a detailed documentation about how to add his tree component to Job page

2. The functionalities in eureka.job.js file needs to be added to job controller, mainly is poll() function and save() function

**Comment by arpost** [comment]
I finished this.
