### ISSUE TITLE
Home page first time loading logic, performance may need to be improved

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#19]
Currently logic:
Only when userVerficationPerformed == true, then the banner actually shows.
    -If the user already logged in, the 4 menu items show
    -If the user not already logged in, the login shows

Before user is verified, the banner is blank.
Banner only decides what to show, until the user is verified.

Problem is:
If user verification takes long time, like 2 or 3 seconds, this feels like a performance issue. Or there maybe a better way to design how the homepage is loaded.

**Comment by arpost** [comment]
Performance is much improved now, so closing.
