### ISSUE TITLE
packagingincludes in eureka-webapp/pom.xml is outdated

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#24]
Has references to app/*, for example, which doesn't exist any longer.

**Comment by candyam5522** [comment]
Just pushed a new commit to resolve this, thanks

**Comment by arpost** [comment]
This is a different issue. The packagingincludes tag refers mostly to files that no longer exist. The purpose of the tag is to resolve an old issue where the warfile building was pulling in hundreds of megabytes worth of stuff only used in the new client side build process, and the resulting warfile was so big that it took > 30 minutes for tomcat to unpack. This tag and the packagingexcludes tag below it need to be updated, and this issue serves as a reminder that we need to do that at some point.

**Comment by candyam5522** [comment]
Okay, understand now :)

**Comment by arpost** [comment]
I made additional changes as part of the build performance issue.
