### ISSUE TITLE
Version mismatches reported by bower install on compiling eureka-webapp

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#25]
bower install reports:

[INFO] Please note that,
[INFO]     eureka depends on angular#~1.3 which resolved to angular#1.3.20
[INFO]     angular-ui-tree#2.9.0 depends on angular#1.2.x || 1.3.x which resolved to angular#1.3.20
[INFO]     angular-messages#1.3.20 depends on angular#1.3.20 which resolved to angular#1.3.20
[INFO]     angular-animate#1.4.8, angular-aria#1.4.8, angular-mocks#1.4.8 depends on angular#1.4.8 which resolved to angular#1.4.8
[INFO]     angular-material#0.11.4, angular-material#0.11.4 depends on angular#^1.3.0 || >1.4.0-beta.0 which resolved to angular#1.4.8
[INFO]     tg-angular-validator#1.2.8 depends on angular#>=1.3.0 which resolved to angular#1.4.8
[INFO]     ui-router#0.2.15 depends on angular#>= 1.0.8 which resolved to angular#1.4.8
[INFO]     angular-material-data-table#0.8.14 depends on angular#^1.4.0 which resolved to angular#1.4.8
[INFO]     ng-flow#2.6.1 depends on angular#~1 which resolved to angular#1.4.8
[INFO] Resort to using angular#~1.4 which resolved to angular#1.4.8
[INFO] Code incompatibilities may occur.

**Comment by akalsan** [comment]
Bower.json uses semantic versioning in the dependencies tab. 
 "dependencies": {
    "angular": "~1.3",
    "ui-router": "~0.2.15",
    "angular-messages": "~1.3",
    "tg-angular-validator": "~1.2.7",
    "bootstrap": "~3.3",
    "angular-ui-tree": "~2.9.0",
    "font-awesome": "~4.4.0",
    "lodash": "~3.10.1",
    "angular-material": "~0.11.0",
    "angular-material-data-table": "~0.8.11",
    "angular-mocks": "~1.4.7",
    "ng-flow": "~2"
  }
It doesn't mention exact version but a range. The info messages is just informational messages as to what version out of the range bower is using and resolved. in case there is a conflict, the resolutions tab helps in resolving.
"resolutions": {
    "angular": "~1.4"
  }, 
But the above messages are not indicating any conflicts but message to the user as what version of the dependency is being used.
