### ISSUE TITLE
Make app-properties.js dynamically populate from a REST service

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#27]
Some of the configuration here is duplicated in the application.properties mechanism, and some configuration information from application.properties is not here at all (like enabling OAuth-based authentication). We need a mechanism for selected properties from application.properties to be available from a web service.

**Comment by arpost** [comment]
Here are the app properties to put in the REST endpoint (see WebappProperties.java):

- ephiProhibited
- demoMode
- oAuthRegistrationEnabled
- googleOAuthRegistrationEnabled*
- gitHubOAuthRegistrationEnabled*
- twitterOAuthRegistrationEnabled*
- globusOAuthRegistrationEnabled* 
- localAccountRegistrationEnabled
- registrationEnabled
- supportUri

*might want to replace the marked methods with a single getOAuthRegistrationProviders method that returns an array/list of provider names.

**Comment by candyam5522** [comment]
Okay, will do

**Comment by candyam5522** [comment]
in the original js file(hardcoded):
        aiwSiteUrl: 'http://aiw.sourceforge.net',
        helpSiteUrl: 'http://aiw.sourceforge.net/help/v1-10',
        organizationName: 'Emory University',

Now we have three beans: 
appproperties/mode, 
appproperties/registration, 
appproperties/supporturi

**Comment by arpost** [comment]
Rename the "supporturi" endpoint "links", and put aiwSiteUrl, helpSiteUrl and organizationName in there.

**Comment by candyam5522** [comment]
Okay
