### ISSUE TITLE
Stack trace on saving superuser from admin page if admin and researcher roles are unselected

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#41]

**Comment by candyam5522** [comment]
Stack trace if both admin and researcher roles are unselected:
HTTP Status 500 - Error saving user

type Exception report

message Error saving user

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Error saving user
	edu.emory.cci.aiw.cvrg.eureka.servlet.worker.admin.SaveUserWorker.execute(SaveUserWorker.java:93)
	edu.emory.cci.aiw.cvrg.eureka.servlet.AdminManagerServlet.doGet(AdminManagerServlet.java:91)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.PasswordExpiredFilter.doFilter(PasswordExpiredFilter.java:133)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.UserInfoFilter.doFilter(UserInfoFilter.java:87)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.HaveUserRecordFilter.doFilter(HaveUserRecordFilter.java:101)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.MessagesFilter.doFilter(MessagesFilter.java:84)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.common.filter.RolesFilter.doFilter(RolesFilter.java:139)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:54)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:75)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:201)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:107)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
root cause

edu.emory.cci.aiw.cvrg.eureka.common.comm.clients.ClientException: 
	edu.emory.cci.aiw.cvrg.eureka.common.comm.clients.EurekaClient.errorIf(EurekaClient.java:257)
	edu.emory.cci.aiw.cvrg.eureka.common.comm.clients.EurekaClient.errorIfStatusNotEqualTo(EurekaClient.java:236)
	edu.emory.cci.aiw.cvrg.eureka.common.comm.clients.EurekaClient.doPut(EurekaClient.java:97)
	edu.emory.cci.aiw.cvrg.eureka.common.comm.clients.ServicesClient.updateUser(ServicesClient.java:156)
	edu.emory.cci.aiw.cvrg.eureka.servlet.worker.admin.SaveUserWorker.execute(SaveUserWorker.java:91)
	edu.emory.cci.aiw.cvrg.eureka.servlet.AdminManagerServlet.doGet(AdminManagerServlet.java:91)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.PasswordExpiredFilter.doFilter(PasswordExpiredFilter.java:133)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.UserInfoFilter.doFilter(UserInfoFilter.java:87)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.HaveUserRecordFilter.doFilter(HaveUserRecordFilter.java:101)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.servlet.filter.MessagesFilter.doFilter(MessagesFilter.java:84)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	edu.emory.cci.aiw.cvrg.eureka.common.filter.RolesFilter.doFilter(RolesFilter.java:139)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:54)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:75)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:201)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:107)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)

**Comment by candyam5522** [comment]
SAME error if researcher is selected and admin is unselected.
But NO error if researcher is unselected and admin is selected.

**Comment by arpost** [comment]
Sounds like the role validation needs to be fixed server side. It should be "zero or more valid roles".
