### ISSUE TITLE
Name displayed incorrectly on the  Eureka! UI when first name and last name is null

### ISSUE THREAD

**Issue by akalsan** [eurekaclinical/eureka#61]
The correct behavior seems to be that when the first name and last name is null, the username needs to be displayed on the top right have side of the Eureka! logo. currently when first name and last name is null the name shows something like (null):(null)

**Comment by arpost** [comment]
We need to define a logic for how the user's name is displayed and make sure it is implemented the same way everywhere a name is displayed. I propose the following rule:

1) If full name is not null, then use full name.
2) Use first name + last name if at least one of them is not null.
3) Use the username.
