### ISSUE TITLE
gulp-angular-templatecache issue

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#95]
There is an issue with this plugin (https://www.npmjs.com/package/gulp-angular-templatecache)
For now, in order to build successfully, commented out cache-templates task in gulpfile.js
## 1. comment out cache-templates task
![screen shot 2016-06-17 at 3 06 30 pm](https://cloud.githubusercontent.com/assets/5263886/16161776/62d1be08-349d-11e6-9953-e120a5faa2cf.png)

And modify process-js task
## 3. delete src('./build/templates.js') in process-js 
So process-js task should looks like this:
![screen shot 2016-06-17 at 3 06 20 pm](https://cloud.githubusercontent.com/assets/5263886/16161782/6c3cdfc2-349d-11e6-81ae-2b189d4aebec.png)

**Comment by arpost** [comment]
The gulp-angular-templatecache project has multiple issue reports about this problem. The recommended solution is to add the following to package.json until the problem is fixed:
```
"gulp-header": "1.8.2"
```
See https://github.com/miickel/gulp-angular-templatecache/pull/125
and
https://github.com/tracker1/gulp-header/issues/37

**Comment by candyam5522** [comment]
Error msg:
[INFO] --- frontend-maven-plugin:1.0:gulp (gulp build) @ eureka-webapp ---
[INFO] Running 'gulp.js build' in /Users/miaoai/NetBeansProjects/eureka/eureka-webapp/src/main/webapp
[INFO] [11:35:04] Using gulpfile ~/NetBeansProjects/eureka/eureka-webapp/src/main/webapp/gulpfile.js
[INFO] [11:35:04] Starting 'less'...
[INFO] [11:35:04] Starting 'lint'...
[INFO] [11:35:04] Finished 'lint' after 17 ms
[INFO] [11:35:04] Starting 'cache-templates'...
[INFO] [11:35:04] Starting 'bower'...
[INFO] [11:35:04] Finished 'bower' after 2.4 ms
[INFO] [11:35:04] Finished 'less' after 296 ms
[ERROR] fs.js:839
[ERROR]   return binding.lstat(pathModule._makeLong(path));
[ERROR]                  ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, lstat '/Users/miaoai/NetBeansProjects/eureka/eureka-webapp/src/main/webapp/eureka/templates.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:839:18)

**Comment by arpost** [comment]
Confirmed that nailing down the gulp-header version allows the build to continue.

**Comment by candyam5522** [comment]
There is a fix now. Upgrade to 2.0.0 should resolve the problem. Tested in eureka already, application can be built successfully and run okay now
