### ISSUE TITLE
Change password dialog is misaligned

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#98]
On the account settings page, the form labels are all misaligned. They should be left-justified and closer to the corresponding text field.

![screen shot 2016-06-20 at 6 42 31 pm](https://cloud.githubusercontent.com/assets/5026087/16212585/d543a8d6-3716-11e6-80df-9c4cc44ec0f2.png)

**Comment by arpost** [comment]
Also, please remove the colons. We don't seem to use them anywhere else.

**Comment by candyam5522** [comment]
<img width="539" alt="screen shot 2016-07-06 at 1 16 08 pm" src="https://cloud.githubusercontent.com/assets/5263886/16627578/dfcf66de-437b-11e6-9b97-30ecaa9aade6.png">
<img width="543" alt="screen shot 2016-07-06 at 1 16 19 pm" src="https://cloud.githubusercontent.com/assets/5263886/16627577/dfce76de-437b-11e6-8878-87dfe8b91815.png">
I have modified the code, do you think the current layout looks good? If so I will pull a request

**Comment by candyam5522** [comment]
<img width="568" alt="screen shot 2016-07-06 at 1 19 46 pm" src="https://cloud.githubusercontent.com/assets/5263886/16627680/564b0b2e-437c-11e6-852d-ca07f50365cc.png">

**Comment by candyam5522** [comment]
<img width="574" alt="screen shot 2016-07-06 at 1 19 34 pm" src="https://cloud.githubusercontent.com/assets/5263886/16627686/5b5d359c-437c-11e6-851b-fce3918b0c78.png">

**Comment by arpost** [comment]
Looks good!

Andrew
